development:
  address: "smtp.gmail.com"
  port: 25
  domain: "gmail.com"
  authentication: "plain"
  user_name: "sage.ts920126@gmail.com"
  password: "philosopher920126"
  enable_starttls_auto: true

#Gmail setting: https://support.google.com/a/answer/176600?hl=en
