development:
  address: "smtp.gmail.com"
  port: 25
  domain: "gmail.com"
  authentication: "plain"
  user_name: <%= ENV["action_mailer_user_name"] %>
  password: <%= ENV["action_mailer_password"] %>
  enable_starttls_auto: true

#Gmail setting: https://support.google.com/a/answer/176600?hl=en
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: <%= ENV["action_mailer_user_name"] %>
  password: <%= ENV["action_mailer_password"] %>
  enable_starttls_auto: true